# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'task5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for task5
	pod ‘Alamofire’ 
	pod 'SwiftyJSON’ 
	pod 'M13Checkbox'
	pod 'BEMCheckBox'

  target 'task5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'task5UITests' do
    # Pods for testing
  end

end
